// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUoX4JIvMbmeKXWFefuFXwwo2b1gpobkc',
    appId: '1:543654006969:web:385afc23f09609a87d0b68',
    messagingSenderId: '543654006969',
    projectId: 'fir-flutter-d30ac',
    authDomain: 'fir-flutter-d30ac.firebaseapp.com',
    storageBucket: 'fir-flutter-d30ac.appspot.com',
    measurementId: 'G-K9NF3144ZF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXo818ChvjDHv0x5DNvNLqnV-6nnlEKPw',
    appId: '1:543654006969:android:56759a6b3a666f617d0b68',
    messagingSenderId: '543654006969',
    projectId: 'fir-flutter-d30ac',
    storageBucket: 'fir-flutter-d30ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWCNnLXTr9m7T8TqW16tYhc1fl6zdhbzU',
    appId: '1:543654006969:ios:24b33c1b33992acc7d0b68',
    messagingSenderId: '543654006969',
    projectId: 'fir-flutter-d30ac',
    storageBucket: 'fir-flutter-d30ac.appspot.com',
    iosClientId: '543654006969-i9j74924l2s1o2mhl1hqn43blhj1mvng.apps.googleusercontent.com',
    iosBundleId: 'com.niran.firebaselearn.firebaseLearn',
  );
}
